name: Bug Report
description: Report of critical bug such as UX inconsistencies, logical contradictions and functional shortcomings.
labels: 'Bug Report'
body:
  - type: dropdown
    id: bug_type
    attributes:
      label: Bug Type
      description: Select the bug type
      options:
        - App crashed
        - App froze
        - Function not working
        - Data damaged
        - Performance
        - UX inconsistency
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Title
      description: Clear title
      placeholder: Briefly describe the bug
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction steps
      description: Steps to reproduce a bug
      placeholder: 1. Click diamond 2. HODL
    validations:
      required: true
  - type: textarea
    id: actual-result
    attributes:
      label: Actual result
      description: What was seen
      placeholder: When action is done, something happens
    validations:
      required: true
  - type: textarea
    id: expected-result
    attributes:
      label: Expected result
      description: What was expected
      placeholder: When action is done, nothing happens
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Severity of the bug
      options:
        - Vulnerability
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true